/**
 * Multi-chart split grid (platform feature). The MODEL — split tree, cell registry, cumulative
 * split count, per-cell ages, and the paywall cap — is engine-owned (`aion_engine::Workspace`,
 * headless-tested); this package layer is the thin browser bridge: it mirrors the engine's
 * layout tree into flex DOM, and owns one full `create_chart` instance per leaf cell (its own
 * scales, series, chart type, and drawing primitives — splitting never shares state).
 *
 * Paywall metering is the engine's usage snapshot, re-emitted on every topology change (and
 * optionally on a heartbeat), with a hard `max_charts` cap and an `on_split_request` veto hook
 * for platform-side limits.
 */

// The wasm glue is generated by `wasm-pack` into ../pkg (see `npm run build:wasm`).
// @ts-ignore -- pkg is a build artifact, present after build:wasm
import { AionWorkspace } from "../pkg/aion_wasm.js";
import { create_chart } from "./index.js";
import { ensure_init } from "./impl.js";
import type { chart_api, chart_options, deep_partial } from "./types.js";

/** `horizontal` places the two charts side by side; `vertical` stacks them. */
export type split_direction = "horizontal" | "vertical";

/** Paywall/metering snapshot (engine `WorkspaceUsage`), emitted on every topology change. */
export interface grid_usage {
  chart_count: number;
  split_count: number;
  elapsed_seconds: number;
  cells: { id: number; age_seconds: number }[];
}

export interface grid_cell {
  readonly id: number;
  readonly chart: chart_api;
  /** The cell's flex slot; per-cell chrome (buttons, legends) attaches here. */
  readonly element: HTMLDivElement;
  readonly created_at: number;
  /**
   * Split this cell in two: the existing chart keeps its state in the first half and a fresh
   * chart (same base options) is created in the second. Resolves to the NEW cell, or `null`
   * when the engine's cap rejects the split.
   */
  split(direction: split_direction): Promise<grid_cell | null>;
  /** Remove this cell: its sibling subtree absorbs the freed space (last cell refuses). */
  remove(): boolean;
}

export interface chart_grid_options {
  /** Base options for every chart the grid creates (the first cell and each split half). */
  chart_options?: deep_partial<chart_options>;
  /** Hard cap on live charts (paywall tier), enforced engine-side; `null`/absent = unlimited. */
  max_charts?: number | null;
  /** Veto hook (package-side, evaluated before the engine's cap): return `false` to reject. */
  on_split_request?: (next_count: number) => boolean;
  /** Usage signal sink: called with a fresh engine snapshot on every split/remove. */
  on_usage?: (usage: grid_usage) => void;
  /** Optional heartbeat (ms) re-emitting usage so time-based meters stay current. */
  usage_heartbeat_ms?: number;
  /** The split-divider line color. `null`/absent (the default) FOLLOWS the first chart's
   *  axis border color — the divider is axis chrome, so it tracks the same token (theme and
   *  explicit border changes); an explicit string pins it. */
  divider_color?: string | null;
}

export interface chart_grid {
  cells(): grid_cell[];
  chart_count(): number;
  usage(): grid_usage;
  set_max_charts(n: number | null): void;
  /** Pin a divider color, or pass `null` to re-enter follow mode (divider = axis border). */
  set_divider_color(color: string | null): void;
  destroy(): void;
}

interface cell_record {
  id: number;
  slot: HTMLDivElement;
  host: HTMLDivElement;
  chart: chart_api;
  created_at: number;
  handle: handle_record;
}

// The public handle's `chart` is read-only externally but assigned once the chart resolves
// (the slot attaches and lays out first).
type handle_record = Omit<grid_cell, "chart"> & { chart: chart_api };

const FLEX_CHILD = "flex:1 1 0;min-width:0;min-height:0;position:relative;";
const now_seconds = () => Date.now() / 1000;

interface layout_node {
  kind: "cell" | "split";
  id?: number;
  direction?: "horizontal" | "vertical";
  ratio?: number;
  a?: layout_node;
  b?: layout_node;
}

/**
 * Create a grid holding a single chart in `container`. Split from there via `cell.split(...)`.
 * The container becomes a flex root the grid owns entirely.
 */
export async function create_chart_grid(
  container: HTMLElement,
  options: chart_grid_options = {},
): Promise<chart_grid> {
  await ensure_init(); // the workspace handle touches the wasm module directly
  container.style.display = "flex";
  container.style.overflow = "hidden";
  if (getComputedStyle(container).position === "static") {
    container.style.position = "relative";
  }

  const workspace = new AionWorkspace(now_seconds());
  if (options.max_charts !== undefined && options.max_charts !== null) {
    workspace.set_max_charts(options.max_charts);
  }
  const cells = new Map<number, cell_record>();
  let heartbeat: ReturnType<typeof setInterval> | null = null;
  let divider_color: string | null = options.divider_color ?? null;

  /** The divider line color: the pinned value, or the first chart's axis border color when
   *  following (default) — the divider is axis chrome and tracks the same token. */
  const resolve_divider_color = (): string => {
    if (divider_color !== null) return divider_color;
    const first = cells.values().next().value as cell_record | undefined;
    const border = (
      first?.chart.options() as { rightPriceScale?: { borderColor?: string } } | undefined
    )?.rightPriceScale?.borderColor;
    return border ?? "#d6dcde";
  };

  const usage = (): grid_usage => JSON.parse(workspace.usage_json(now_seconds())) as grid_usage;
  const emit_usage = () => options.on_usage?.(usage());

  /** The adjacent cell ids flanking a split node (its divider's left/top and right/bottom). */
  const edge_ids = (node: layout_node, side: "first" | "last"): number => {
    if (node.kind === "cell") return node.id as number;
    return edge_ids((side === "last" ? node.b : node.a) as layout_node, side);
  };

  /** The draggable split divider: a 1px line with a 5px hit area (padding + background-clip),
   *  col/row cursor per direction. Dragging adjusts the two sides' flex weights live and
   *  persists the final ratio engine-side on release. */
  const make_divider = (
    node: layout_node,
    horizontal: boolean,
    a_el: HTMLElement,
    b_el: HTMLElement,
  ): HTMLDivElement => {
    const div = document.createElement("div");
    div.className = "aion-grid-divider";
    div.style.cssText =
      "flex:0 0 1px;z-index:4;touch-action:none;" +
      `background:${resolve_divider_color()};background-clip:content-box;` +
      `cursor:${horizontal ? "col-resize" : "row-resize"};` +
      (horizontal ? "margin:0 -2px;padding:0 2px;" : "margin:-2px 0;padding:2px 0;");
    div.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      div.setPointerCapture(e.pointerId);
      const start_ratio = node.ratio ?? 0.5;
      const left_id = edge_ids(node.a as layout_node, "last");
      const right_id = edge_ids(node.b as layout_node, "first");
      const start_pos = horizontal ? e.clientX : e.clientY;
      const parent_size =
        (div.parentElement as HTMLElement).getBoundingClientRect()[horizontal ? "width" : "height"] || 1;
      let current = start_ratio;
      const on_move = (ev: PointerEvent) => {
        const delta = ((horizontal ? ev.clientX : ev.clientY) - start_pos) / parent_size;
        current = Math.min(0.95, Math.max(0.05, start_ratio + delta));
        // Live: re-weight the two sides without rebuilding the layout (the divider being
        // dragged must stay put); the engine persists the ratio on release.
        a_el.style.flexGrow = String(current);
        b_el.style.flexGrow = String(1 - current);
      };
      const on_up = () => {
        div.removeEventListener("pointermove", on_move);
        div.removeEventListener("pointerup", on_up);
        div.removeEventListener("pointercancel", on_up);
        if (current !== start_ratio) {
          workspace.resize_between(left_id, right_id, current - start_ratio);
          reconcile();
        }
      };
      div.addEventListener("pointermove", on_move);
      div.addEventListener("pointerup", on_up);
      div.addEventListener("pointercancel", on_up);
    });
    return div;
  };

  const make_slot = (): { slot: HTMLDivElement; host: HTMLDivElement } => {
    const slot = document.createElement("div");
    slot.style.cssText = FLEX_CHILD;
    const host = document.createElement("div");
    host.style.cssText = "position:absolute;inset:0;";
    slot.appendChild(host);
    return { slot, host };
  };

  const add_chart = async (id: number): Promise<cell_record> => {
    const { slot, host } = make_slot();
    const record: cell_record = {
      id,
      slot,
      host,
      chart: null as unknown as chart_api,
      created_at: Date.now(),
      handle: null as unknown as grid_cell,
    };
    record.handle = {
      id,
      chart: null as unknown as chart_api,
      element: slot,
      created_at: record.created_at,
      split: (direction) => split(record, direction),
      remove: () => remove(record),
    } as handle_record;
    cells.set(id, record);
    // The slot must be ATTACHED (real size) before the chart measures its container: a
    // detached host reads 0×0, the first fit packs at minimum spacing, and the later
    // auto-resize explodes the visible range.
    reconcile();
    record.chart = await create_chart(host, { autoSize: true, ...options.chart_options });
    record.handle.chart = record.chart;
    return record;
  };

  /** Mirror the engine's layout tree into the DOM, reusing cell slots by id (chart DOM/state
   *  is never rebuilt — only the split wrappers are). */
  const reconcile = () => {
    const build = (node: layout_node): HTMLElement => {
      if (node.kind === "cell") {
        const record = cells.get(node.id as number);
        if (!record) throw new Error(`aion grid: engine cell ${node.id} has no chart`);
        return record.slot;
      }
      const horizontal = node.direction === "horizontal";
      const ratio = node.ratio ?? 0.5;
      const div = document.createElement("div");
      div.style.cssText = `${FLEX_CHILD}display:flex;flex-direction:${horizontal ? "row" : "column"};`;
      const a_el = build(node.a as layout_node);
      const b_el = build(node.b as layout_node);
      a_el.style.flexGrow = String(ratio);
      b_el.style.flexGrow = String(1 - ratio);
      div.appendChild(a_el);
      div.appendChild(make_divider(node, horizontal, a_el, b_el));
      div.appendChild(b_el);
      return div;
    };
    const layout = JSON.parse(workspace.layout_json()) as layout_node;
    container.replaceChildren(build(layout));
  };

  const split = async (cell: cell_record, direction: split_direction): Promise<grid_cell | null> => {
    const next_count = cells.size + 1;
    if (options.on_split_request?.(next_count) === false) return null;
    const new_id = Number(workspace.split(cell.id, direction, now_seconds()));
    if (new_id < 0) return null; // engine cap (paywall tier) or unknown cell
    const created = await add_chart(new_id);
    reconcile();
    emit_usage();
    return created.handle;
  };

  const remove = (cell: cell_record): boolean => {
    if (!workspace.remove(cell.id)) return false; // unknown id or the last chart
    cell.chart.remove();
    cell.slot.remove();
    cells.delete(cell.id);
    reconcile();
    emit_usage();
    return true;
  };

  // The root chart (engine cell id 1).
  const root_id = (JSON.parse(workspace.cell_ids_json()) as number[])[0] as number;
  await add_chart(root_id);
  reconcile();

  if (options.usage_heartbeat_ms && options.usage_heartbeat_ms > 0) {
    heartbeat = setInterval(emit_usage, options.usage_heartbeat_ms);
  }
  emit_usage();

  return {
    cells: () =>
      (JSON.parse(workspace.cell_ids_json()) as number[]).map((id) => cells.get(id)!.handle),
    chart_count: () => workspace.chart_count(),
    usage,
    set_max_charts: (n) => workspace.set_max_charts(n ?? undefined),
    set_divider_color: (color) => {
      divider_color = color;
      reconcile();
    },    destroy: () => {
      if (heartbeat !== null) clearInterval(heartbeat);
      for (const cell of cells.values()) cell.chart.remove();
      cells.clear();
      container.replaceChildren();
      container.style.display = "";
      container.style.overflow = "";
    },
  };
}
