/**
 * Multi-chart split grid (platform feature). The MODEL — split tree, cell registry, cumulative
 * split count, per-cell ages, and the paywall cap — is engine-owned (`origin_engine::Workspace`,
 * headless-tested); this package layer is the thin browser bridge: it mirrors the engine's
 * layout tree into flex DOM, and owns one full `create_chart` instance per leaf cell (its own
 * scales, series, chart type, and drawing primitives — splitting never shares state).
 *
 * Paywall metering is the engine's usage snapshot, re-emitted on every topology change (and
 * optionally on a heartbeat), with a hard `max_charts` cap and an `on_split_request` veto hook
 * for platform-side limits.
 */

// The wasm glue is generated by `wasm-pack` into ../pkg (see `npm run build:wasm`).
// @ts-ignore -- pkg is a build artifact, present after build:wasm
import { OriginWorkspace } from "../pkg/origin_wasm.js";
import { create_chart } from "./index.js";
import { ensure_init } from "./impl.js";
import { DEFAULT_SHORTCUTS, install_shortcuts } from "./shortcuts.js";
import type { shortcut_action } from "./shortcuts.js";
import type { chart_api, chart_options, deep_partial } from "./types.js";

/** `horizontal` places the two charts side by side; `vertical` stacks them. */
export type split_direction = "horizontal" | "vertical";

/** Paywall/metering snapshot (engine `WorkspaceUsage`), emitted on every topology change. */
export interface grid_usage {
  chart_count: number;
  split_count: number;
  elapsed_seconds: number;
  cells: { id: number; age_seconds: number }[];
}

export interface grid_cell {
  readonly id: number;
  readonly chart: chart_api;
  /** The cell's flex slot; per-cell chrome (buttons, legends) attaches here. */
  readonly element: HTMLDivElement;
  readonly created_at: number;
  /**
   * Split this cell in two: the existing chart keeps its state in the first half and a fresh
   * chart (same base options) is created in the second. Resolves to the NEW cell, or `null`
   * when the engine's cap rejects the split.
   */
  split(direction: split_direction): Promise<grid_cell | null>;
  /** Remove this cell: its sibling subtree absorbs the freed space (last cell refuses). */
  remove(): boolean;
}

export interface chart_grid_options {
  /** Base options for every chart the grid creates (the first cell and each split half). */
  chart_options?: deep_partial<chart_options>;
  /** Hard cap on live charts (paywall tier), enforced engine-side; `null`/absent = unlimited. */
  max_charts?: number | null;
  /** Veto hook (package-side, evaluated before the engine's cap): return `false` to reject. */
  on_split_request?: (next_count: number) => boolean;
  /** Usage signal sink: called with a fresh engine snapshot on every split/remove. */
  on_usage?: (usage: grid_usage) => void;
  /** Optional heartbeat (ms) re-emitting usage so time-based meters stay current. */
  usage_heartbeat_ms?: number;
  /** The split-divider line color. `null`/absent (the default) FOLLOWS the first chart's
   *  axis border color — the divider is axis chrome, so it tracks the same token (theme and
   *  explicit border changes); an explicit string pins it. */
  divider_color?: string | null;
  /** Split shortcuts: `true` uses the engine defaults (shortcuts.ts `DEFAULT_SHORTCUTS`), an
   *  object overrides individual combos (e.g. `{ "grid.split_vertical": "ctrl+shift+x" }`).
   *  Default `false` (no shortcuts). Keys never fire while typing in a field. */
  shortcuts?: boolean | Partial<Record<shortcut_action, string>>;
  /** Fired for every cell created by a split (button or shortcut path): the platform's hook
   *  to seed/configure the fresh chart (data, theme, chrome). */
  on_cell_added?: (cell: grid_cell) => void;
}

export interface chart_grid {
  cells(): grid_cell[];
  chart_count(): number;
  usage(): grid_usage;
  set_max_charts(n: number | null): void;
  /** Pin a divider color, or pass `null` to re-enter follow mode (divider = axis border). */
  set_divider_color(color: string | null): void;
  /** The active cell (the last one pointer-pressed) — the target of the split shortcuts. */
  active_cell(): grid_cell;
  /** Maximize a cell to the full container (the others + dividers hide), or pass `null` to
   *  restore. Ctrl/Cmd+click on a cell toggles this (TradingView's maximize pane). */
  maximize(cell: grid_cell | null): void;
  /** The maximized cell, or `null` when the grid is in its normal layout. */
  maximized_cell(): grid_cell | null;
  destroy(): void;
}

interface cell_record {
  id: number;
  slot: HTMLDivElement;
  host: HTMLDivElement;
  chart: chart_api;
  created_at: number;
  handle: handle_record;
}

// The public handle's `chart` is read-only externally but assigned once the chart resolves
// (the slot attaches and lays out first).
type handle_record = Omit<grid_cell, "chart"> & { chart: chart_api };

const FLEX_CHILD = "flex:1 1 0;min-width:0;min-height:0;position:relative;";
const now_seconds = () => Date.now() / 1000;

interface layout_node {
  kind: "cell" | "split";
  id?: number;
  direction?: "horizontal" | "vertical";
  ratio?: number;
  a?: layout_node;
  b?: layout_node;
}

/**
 * Create a grid holding a single chart in `container`. Split from there via `cell.split(...)`.
 * The container becomes a flex root the grid owns entirely.
 */
export async function create_chart_grid(
  container: HTMLElement,
  options: chart_grid_options = {},
): Promise<chart_grid> {
  await ensure_init(); // the workspace handle touches the wasm module directly
  container.style.display = "flex";
  container.style.overflow = "hidden";
  if (getComputedStyle(container).position === "static") {
    container.style.position = "relative";
  }

  const workspace = new OriginWorkspace(now_seconds());
  if (options.max_charts !== undefined && options.max_charts !== null) {
    workspace.set_max_charts(options.max_charts);
  }
  const cells = new Map<number, cell_record>();
  let heartbeat: ReturnType<typeof setInterval> | null = null;
  let divider_color: string | null = options.divider_color ?? null;

  /** The divider line color: the pinned value, or the first chart's axis border color when
   *  following (default) — the divider is axis chrome and tracks the same token. */
  const resolve_divider_color = (): string => {
    if (divider_color !== null) return divider_color;
    const first = cells.values().next().value as cell_record | undefined;
    const border = (
      first?.chart.options() as { rightPriceScale?: { borderColor?: string } } | undefined
    )?.rightPriceScale?.borderColor;
    return border ?? "#d6dcde";
  };

  const usage = (): grid_usage => JSON.parse(workspace.usage_json(now_seconds())) as grid_usage;
  const emit_usage = () => options.on_usage?.(usage());

  /** The live divider elements (rebuilt by `reconcile`), repainted when the follow-source
   *  chart's options change (the axis border token is live, not sampled once). */
  const dividers = new Set<{ el: HTMLDivElement; horizontal: boolean }>();
  /** Paint a divider's line as a solid strip snapped to the ABSOLUTE device-pixel grid:
   *  exactly `max(1, floor(dpr))` device pixels at full coverage — the same hairline the
   *  canvas axis border draws (inner_render border_w). A CSS gradient band can't do this
   *  (its stop edges anti-alias at fractional positions into a washed-out 2px line), and a
   *  fractional transform re-samples the same way — so the strip is POSITIONED (never
   *  transformed) on an integer device boundary, re-measured at paint time and on restyle. */
  const paint_divider = (el: HTMLDivElement, horizontal: boolean) => {
    requestAnimationFrame(() => {
      if (!el.isConnected) return;
      const dpr = window.devicePixelRatio || 1;
      const device_w = Math.max(1, Math.floor(dpr));
      const w = device_w / dpr; // css px per full-coverage device pixel(s)
      const rect = el.getBoundingClientRect();
      const edge = horizontal ? rect.left : rect.top;
      const size = horizontal ? rect.width : rect.height;
      const aligned_dev = Math.round((edge + size / 2) * dpr - device_w / 2);
      const offset = aligned_dev / dpr - edge;
      let inner = el.firstElementChild as HTMLDivElement | null;
      if (inner === null) {
        inner = document.createElement("div");
        el.appendChild(inner);
      }
      inner.style.cssText = horizontal
        ? `position:absolute;top:0;bottom:0;left:${offset}px;width:${w}px;background:${resolve_divider_color()};`
        : `position:absolute;left:0;right:0;top:${offset}px;height:${w}px;background:${resolve_divider_color()};`;
    });
  };
  /** Re-resolve and repaint every divider (axis border changed, or a pinned color was set). */
  const restyle_dividers = () => {
    for (const { el, horizontal } of dividers) paint_divider(el, horizontal);
  };

  /** The adjacent cell ids flanking a split node (its divider's left/top and right/bottom). */
  const edge_ids = (node: layout_node, side: "first" | "last"): number => {
    if (node.kind === "cell") return node.id as number;
    return edge_ids((side === "last" ? node.b : node.a) as layout_node, side);
  };

  /** The draggable split divider: a 5px hit area consuming 1px of layout (negative margins),
   *  col/row cursor per direction. The visible line is a solid inner strip snapped to the
   *  device-pixel grid (see `paint_divider`), so it matches the canvas axis border's hairline
   *  under any DPR and any host-page `box-sizing` reset. Dragging adjusts the two sides' flex
   *  weights live and persists the final ratio engine-side on release. */
  const make_divider = (
    node: layout_node,
    horizontal: boolean,
    a_el: HTMLElement,
    b_el: HTMLElement,
  ): HTMLDivElement => {
    const div = document.createElement("div");
    div.className = "origin-grid-divider";
    div.style.cssText =
      "flex:0 0 5px;position:relative;z-index:4;touch-action:none;" +
      `cursor:${horizontal ? "col-resize" : "row-resize"};` +
      (horizontal ? "margin:0 -2px;" : "margin:-2px 0;");
    paint_divider(div, horizontal);
    dividers.add({ el: div, horizontal });
    div.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      div.setPointerCapture(e.pointerId);
      const start_ratio = node.ratio ?? 0.5;
      const left_id = edge_ids(node.a as layout_node, "last");
      const right_id = edge_ids(node.b as layout_node, "first");
      const start_pos = horizontal ? e.clientX : e.clientY;
      const parent_size =
        (div.parentElement as HTMLElement).getBoundingClientRect()[horizontal ? "width" : "height"] || 1;
      let current = start_ratio;
      const on_move = (ev: PointerEvent) => {
        const delta = ((horizontal ? ev.clientX : ev.clientY) - start_pos) / parent_size;
        current = Math.min(0.95, Math.max(0.05, start_ratio + delta));
        // Live: re-weight the two sides without rebuilding the layout (the divider being
        // dragged must stay put); the engine persists the ratio on release.
        a_el.style.flexGrow = String(current);
        b_el.style.flexGrow = String(1 - current);
      };
      const on_up = () => {
        div.removeEventListener("pointermove", on_move);
        div.removeEventListener("pointerup", on_up);
        div.removeEventListener("pointercancel", on_up);
        if (current !== start_ratio) {
          workspace.resize_between(left_id, right_id, current - start_ratio);
          reconcile();
        }
      };
      div.addEventListener("pointermove", on_move);
      div.addEventListener("pointerup", on_up);
      div.addEventListener("pointercancel", on_up);
    });
    return div;
  };

  const make_slot = (): { slot: HTMLDivElement; host: HTMLDivElement } => {
    const slot = document.createElement("div");
    slot.style.cssText = FLEX_CHILD;
    const host = document.createElement("div");
    host.style.cssText = "position:absolute;inset:0;";
    slot.appendChild(host);
    return { slot, host };
  };

  const add_chart = async (id: number): Promise<cell_record> => {
    const { slot, host } = make_slot();
    const record: cell_record = {
      id,
      slot,
      host,
      chart: null as unknown as chart_api,
      created_at: Date.now(),
      handle: null as unknown as grid_cell,
    };
    record.handle = {
      id,
      chart: null as unknown as chart_api,
      element: slot,
      created_at: record.created_at,
      split: (direction) => split(record, direction),
      remove: () => remove(record),
    } as handle_record;
    cells.set(id, record);
    // The last pointer-pressed cell is the ACTIVE one — the target of the split shortcuts.
    // Ctrl/Cmd+click toggles the cell's full-container maximize (never while a drawing tool is
    // armed on it — a Ctrl+click there is a magnet anchor placement). CAPTURE phase: the
    // chart's gesture layer stops propagation on bubble, which would otherwise eat both.
    slot.addEventListener("pointerdown", (e) => {
      active_id = id;
      if ((e.ctrlKey || e.metaKey) && record.chart !== null && record.chart.active_drawing_tool() === null) {
        toggle_maximize(id);
      }
    }, true);
    // The slot must be ATTACHED (real size) before the chart measures its container: a
    // detached host reads 0×0, the first fit packs at minimum spacing, and the later
    // auto-resize explodes the visible range.
    reconcile();
    record.chart = await create_chart(host, { autoSize: true, ...options.chart_options });
    record.handle.chart = record.chart;
    // The divider follows the first chart's axis border token live: any apply_options on any
    // cell (theme switch, explicit borderColor) repaints the dividers without a topology change.
    record.chart.subscribe_options_change(restyle_dividers);
    return record;
  };

  /** Mirror the engine's layout tree into the DOM, reusing cell slots by id (chart DOM/state
   *  is never rebuilt — only the split wrappers are). */
  const reconcile = () => {
    const build = (node: layout_node): HTMLElement => {
      if (node.kind === "cell") {
        const record = cells.get(node.id as number);
        if (!record) throw new Error(`origin grid: engine cell ${node.id} has no chart`);
        return record.slot;
      }
      const horizontal = node.direction === "horizontal";
      const ratio = node.ratio ?? 0.5;
      const div = document.createElement("div");
      div.style.cssText = `${FLEX_CHILD}display:flex;flex-direction:${horizontal ? "row" : "column"};`;
      const a_el = build(node.a as layout_node);
      const b_el = build(node.b as layout_node);
      a_el.style.flexGrow = String(ratio);
      b_el.style.flexGrow = String(1 - ratio);
      div.appendChild(a_el);
      div.appendChild(make_divider(node, horizontal, a_el, b_el));
      div.appendChild(b_el);
      return div;
    };
    const layout = JSON.parse(workspace.layout_json()) as layout_node;
    // The split wrappers (and their dividers) are rebuilt wholesale; cell slots are reused.
    dividers.clear();
    container.replaceChildren(build(layout));
    apply_maximize();
  };

  /** The maximized cell id (full container), or `null` in the normal layout. */
  let maximized_id: number | null = null;
  /** Apply the maximize state: the maximized cell takes the container; the other cells and the
   *  dividers hide (`display:none`). The maximized slot also gets an explicit `1 1 100%` flex —
   *  its ratio weight would otherwise cap it at exactly its share: with a flex-grow sum < 1 the
   *  spec distributes free space UN-normalized, so a 0.5-weight slot stays at 50% even alone. */
  const apply_maximize = () => {
    for (const record of cells.values()) {
      const on = maximized_id === null || record.id === maximized_id;
      record.slot.style.display = on ? "" : "none";
      if (maximized_id !== null && record.id === maximized_id) {
        record.slot.style.flex = "1 1 100%";
      }
    }
    container.querySelectorAll(".origin-grid-divider").forEach((el) => {
      (el as HTMLElement).style.display = maximized_id === null ? "" : "none";
    });
  };
  /** Set (or clear) the maximized cell; clearing rebuilds the layout so the engine's split
   *  ratios win their flex weights back (the maximize override replaced them). */
  const set_maximized = (id: number | null) => {
    maximized_id = id;
    if (maximized_id === null) {
      for (const record of cells.values()) record.slot.style.flex = "";
      reconcile(); // re-derives the ratio weights; its tail reapplies the (now-clear) state
      return;
    }
    apply_maximize();
  };
  /** Ctrl/Cmd+click semantics: maximize the cell, or restore when it's already maximized. */
  const toggle_maximize = (id: number) => {
    set_maximized(maximized_id === id ? null : id);
  };

  const split = async (cell: cell_record, direction: split_direction): Promise<grid_cell | null> => {
    const next_count = cells.size + 1;
    if (options.on_split_request?.(next_count) === false) return null;
    const new_id = Number(workspace.split(cell.id, direction, now_seconds()));
    if (new_id < 0) return null; // engine cap (paywall tier) or unknown cell
    const created = await add_chart(new_id);
    reconcile();
    // One hook for every split path (button or shortcut): the platform seeds the fresh cell.
    options.on_cell_added?.(created.handle);
    emit_usage();
    return created.handle;
  };

  const remove = (cell: cell_record): boolean => {
    if (!workspace.remove(cell.id)) return false; // unknown id or the last chart
    cell.chart.unsubscribe_options_change(restyle_dividers);
    cell.chart.remove();
    cell.slot.remove();
    cells.delete(cell.id);
    // The active target moves to a surviving cell when the active one leaves.
    if (active_id === cell.id) {
      active_id = cells.keys().next().value as number;
    }
    reconcile();
    emit_usage();
    return true;
  };

  // The root chart (engine cell id 1).
  const root_id = (JSON.parse(workspace.cell_ids_json()) as number[])[0] as number;
  let active_id = root_id;
  await add_chart(root_id);
  reconcile();

  // A window resize or DPR change (moving across monitors) shifts every divider off the
  // device grid — repaint them so the line keeps full device-pixel coverage.
  const on_window_resize = () => restyle_dividers();
  window.addEventListener("resize", on_window_resize);

  /** Install the split shortcuts from the registry (shortcuts.ts): defaults, with any
   *  platform overrides merged in. */
  const detach_shortcuts =
    options.shortcuts === undefined || options.shortcuts === false
      ? null
      : install_shortcuts(
          (["grid.split_horizontal", "grid.split_vertical"] as const).map((action) => ({
            combo:
              (typeof options.shortcuts === "object" ? options.shortcuts[action] : undefined) ??
              DEFAULT_SHORTCUTS[action].combo,
            run: () => {
              const cell = cells.get(active_id);
              if (cell !== undefined) {
                void split(cell, action === "grid.split_horizontal" ? "horizontal" : "vertical");
              }
            },
          })),
        );

  if (options.usage_heartbeat_ms && options.usage_heartbeat_ms > 0) {
    heartbeat = setInterval(emit_usage, options.usage_heartbeat_ms);
  }
  emit_usage();

  return {
    cells: () =>
      (JSON.parse(workspace.cell_ids_json()) as number[]).map((id) => cells.get(id)!.handle),
    chart_count: () => workspace.chart_count(),
    usage,
    set_max_charts: (n) => workspace.set_max_charts(n ?? undefined),
    set_divider_color: (color) => {
      divider_color = color;
      reconcile();
    },
    active_cell: () => cells.get(active_id)!.handle,
    maximize: (cell) => set_maximized(cell === null ? null : cell.id),
    maximized_cell: () => {
      const record = maximized_id === null ? undefined : cells.get(maximized_id);
      return record === undefined ? null : record.handle;
    },
    destroy: () => {
      if (heartbeat !== null) clearInterval(heartbeat);
      window.removeEventListener("resize", on_window_resize);
      detach_shortcuts?.();
      for (const cell of cells.values()) {
        cell.chart.unsubscribe_options_change(restyle_dividers);
        cell.chart.remove();
      }
      cells.clear();
      dividers.clear();
      container.replaceChildren();
      container.style.display = "";
      container.style.overflow = "";
    },
  };
}
