// Worker-safe OffscreenCanvas façade. This module deliberately avoids window, document,
// HTMLElement, ResizeObserver, and DOM events; the owning worker relays normalized input samples.

// @ts-ignore -- pkg is generated by build:wasm.
import { create_offscreen_chart as wasm_create_offscreen_chart, NucleusChart } from "../pkg/nucleuscharts_wasm.js";

import { ensure_init } from "./impl.js";
import { default_theme_name, theme_options } from "./theme.js";
import { KIND_TO_U8 } from "./types.js";
import type {
  chart_options,
  deep_partial,
  frame_stats,
  ohlc_columns,
  series_kind,
} from "./types.js";

const FRAME_STATS_SLOT = {
  cpu_ms: 0,
  gpu_ms: 1,
  draw_calls: 2,
  dropped_frames: 3,
  presented_frames: 4,
  memory_bytes: 5,
  canvas2d_ops: 6,
  ring_overruns: 7,
} as const;

const UNSUPPORTED_WORKER_OPTIONS = [
  "autoSize",
  "localization",
  "handle_scroll",
  "handle_scale",
  "kinetic_scroll",
  "tracking_mode",
] as const;

type offscreen_layout_options = Omit<deep_partial<chart_options["layout"]>, "panes"> & {
  panes?: Omit<deep_partial<chart_options["layout"]["panes"]>, "enableResize">;
};

/** Engine-owned options supported by a worker chart. DOM gestures, localization callbacks,
 * ResizeObserver sizing, and pane-separator dragging stay on the DOM `create_chart` façade. */
export type offscreen_chart_options = Omit<
  deep_partial<chart_options>,
  (typeof UNSUPPORTED_WORKER_OPTIONS)[number] | "layout"
> & { layout?: offscreen_layout_options };

function split_offscreen_options(options: offscreen_chart_options): {
  theme: "light" | "dark" | undefined;
  engine: Record<string, unknown>;
} {
  const raw = options as Record<string, unknown>;
  for (const key of UNSUPPORTED_WORKER_OPTIONS) {
    if (key in raw) throw new Error(`nucleuscharts: worker charts do not support option ${key}`);
  }
  const layout = raw.layout as { panes?: Record<string, unknown> } | undefined;
  if (layout?.panes && "enableResize" in layout.panes) {
    throw new Error("nucleuscharts: worker charts do not support option layout.panes.enableResize");
  }
  const { theme, ...engine } = options;
  return { theme, engine: engine as Record<string, unknown> };
}

export interface offscreen_chart_init {
  /** Chart media size in CSS pixels. Workers cannot infer this from a transferred canvas. */
  width: number;
  height: number;
  /** Explicit device-pixel ratio used for both backing stores and engine geometry. */
  dpr: number;
  options?: offscreen_chart_options;
  /** Initial kind for the construction-time primary series (default `candlestick`). */
  series_kind?: series_kind;
  /** Test/runtime hook matching the DOM constructor's deterministic fallback path. */
  force_fallback_adapter?: boolean;
}

export interface offscreen_pointer_event {
  type: "down" | "move" | "up" | "cancel" | "leave";
  /** Full-chart media coordinates, not bitmap coordinates. */
  x: number;
  y: number;
  pointer_id?: number;
  button?: number;
  buttons?: number;
  ctrl_key?: boolean;
  meta_key?: boolean;
  shift_key?: boolean;
}

export interface offscreen_wheel_event {
  /** Full-chart media coordinates. */
  x: number;
  y: number;
  delta_x: number;
  delta_y: number;
  /** 0 = pixels, 1 = lines, 2 = pages (the WheelEvent values). */
  delta_mode?: 0 | 1 | 2;
}

export interface offscreen_key_event {
  key: string;
  ctrl_key?: boolean;
  shift_key?: boolean;
  meta_key?: boolean;
}

/**
 * A chart hosted entirely in a worker. It intentionally exposes the allocation-free typed data
 * path and normalized input injection rather than DOM-only APIs (accessibility, HTML plugins,
 * synchronous screenshots, and ResizeObserver sizing).
 */
export class offscreen_chart {
  private readonly stats_scratch = new Float64Array(NucleusChart.frame_stats_len());
  private readonly active_pointers = new Set<number>();
  private readonly backend_change_handlers = new Set<(backend: "webgpu" | "canvas2d") => void>();
  private primary_adopted = false;
  private drag_pointer_id: number | null = null;
  private removed = false;
  private width: number;
  private height: number;
  private dpr: number;
  private last_backend: "webgpu" | "canvas2d";
  private readonly backend_loss_handler: EventListener;

  constructor(
    private readonly wasm: NucleusChart,
    private readonly gpu_canvas: OffscreenCanvas,
    private readonly fallback_canvas: OffscreenCanvas,
    width: number,
    height: number,
    dpr: number,
  ) {
    this.width = width;
    this.height = height;
    this.dpr = dpr;
    this.last_backend = this.wasm.backend_kind() as "webgpu" | "canvas2d";
    // Device-loss dispatch can occur while a wasm export still owns `NucleusChart`; defer re-entry
    // so wasm-bindgen's recursive-use guard cannot trip.
    this.backend_loss_handler = () => {
      // Rendering performs the actual state transition, then notifies the owner so it can reveal
      // the already-warm fallback HTML canvas.
      queueMicrotask(() => {
        if (!this.removed) this.render();
      });
    };
    globalThis.addEventListener("nucleuscharts-chart-backend-lost", this.backend_loss_handler);
  }

  backend(): "webgpu" | "canvas2d" {
    this.assert_live();
    return this.wasm.backend_kind() as "webgpu" | "canvas2d";
  }

  /** Subscribe to runtime WebGPU → Canvas2D fallback. The owner should reveal the HTML canvas
   * matching `backend`; returns an unsubscribe function. Construction-time backend is available
   * synchronously from {@link backend}. */
  subscribe_backend_change(handler: (backend: "webgpu" | "canvas2d") => void): () => void {
    this.assert_live();
    this.backend_change_handlers.add(handler);
    return () => this.backend_change_handlers.delete(handler);
  }

  /** Adopt the primary series on the first call; later calls append independent series. */
  add_series(kind: series_kind): number {
    this.assert_live();
    if (!this.primary_adopted) {
      this.primary_adopted = true;
      this.wasm.set_series_type(KIND_TO_U8[kind]);
      this.render();
      return 0;
    }
    const id = this.wasm.add_series(KIND_TO_U8[kind]);
    this.render();
    return id;
  }

  set_data_typed(columns: ohlc_columns, series_id = 0): void {
    this.assert_live();
    this.wasm.set_series_data_typed(
      series_id, columns.times, columns.open, columns.high, columns.low, columns.close,
    );
    this.render();
  }

  update_typed(columns: ohlc_columns, series_id = 0): void {
    this.assert_live();
    this.wasm.update_series_bars_typed(
      series_id, columns.times, columns.open, columns.high, columns.low, columns.close,
    );
    this.render();
  }

  apply_options(options: offscreen_chart_options): void {
    this.assert_live();
    const { theme, engine } = split_offscreen_options(options);
    if (theme !== undefined) this.wasm.apply_options(JSON.stringify(theme_options(theme)));
    if (Object.keys(engine).length > 0) this.wasm.apply_options(JSON.stringify(engine));
    this.render();
  }

  fit_content(): void {
    this.assert_live();
    this.wasm.fit_content();
    this.render();
  }

  resize(width: number, height: number, dpr = this.dpr): void {
    this.assert_live();
    this.width = Math.max(width, 1);
    this.height = Math.max(height, 1);
    this.dpr = Math.max(dpr, Number.EPSILON);
    const bitmap_width = Math.max(1, Math.round(this.width * this.dpr));
    const bitmap_height = Math.max(1, Math.round(this.height * this.dpr));
    this.gpu_canvas.width = bitmap_width;
    this.gpu_canvas.height = bitmap_height;
    this.fallback_canvas.width = bitmap_width;
    this.fallback_canvas.height = bitmap_height;
    this.wasm.resize(this.width, this.height, this.dpr);
    this.render();
  }

  render(): void {
    this.assert_live();
    this.wasm.render();
    const backend = this.backend();
    if (backend !== this.last_backend) {
      this.last_backend = backend;
      for (const handler of this.backend_change_handlers) {
        try {
          handler(backend);
        } catch (error) {
          console.error("nucleuscharts: offscreen backend-change handler threw", error);
        }
      }
    }
  }

  /**
   * Inject a normalized pointer sample relayed from the host. Primary-pointer drags pan the time
   * scale; hover/move drives the crosshair. Axis coordinates are accepted but do not begin a pan.
   */
  inject_pointer_event(event: offscreen_pointer_event): void {
    this.assert_live();
    const id = event.pointer_id ?? 1;
    const x = event.x - this.wasm.pane_left();
    const y = event.y;
    const pane_width = this.wasm.time_scale_width();
    const pane_height = this.height - this.wasm.time_scale_height();
    const in_pane = x >= 0 && x <= pane_width && y >= 0 && y <= pane_height;
    const primary = (event.button ?? 0) === 0;

    switch (event.type) {
      case "down":
        if (!primary) return;
        this.active_pointers.add(id);
        if (in_pane && this.drag_pointer_id === null) {
          this.wasm.scroll_start(x);
          this.drag_pointer_id = id;
          this.wasm.set_crosshair(x, y);
        }
        break;
      case "move":
        if (this.drag_pointer_id === id) this.wasm.scroll_move(x);
        if (in_pane || this.drag_pointer_id === id) this.wasm.set_crosshair(x, y);
        else this.wasm.clear_crosshair();
        break;
      case "up":
      case "cancel":
        this.active_pointers.delete(id);
        if (this.drag_pointer_id === id) {
          this.wasm.scroll_end();
          this.drag_pointer_id = null;
        }
        break;
      case "leave":
        if (this.drag_pointer_id !== id) this.wasm.clear_crosshair();
        break;
    }
    this.render();
  }

  /** Inject a relayed wheel sample using the DOM recognizer's delta normalization. */
  inject_wheel_event(event: offscreen_wheel_event): void {
    this.assert_live();
    const adjustment = event.delta_mode === 2 ? 120 : event.delta_mode === 1 ? 32 : 1;
    const delta_x = (adjustment * event.delta_x) / 100;
    const delta_y = -(adjustment * event.delta_y) / 100;
    const pane_left = this.wasm.pane_left();
    const pane_width = this.wasm.time_scale_width();
    if (delta_y !== 0) {
      if (event.x < pane_left || event.x > pane_left + pane_width) {
        this.wasm.price_axis_wheel_zoom(
          this.wasm.pane_index_at_y(event.y),
          event.x < pane_left ? 1 : 0,
          event.y,
          this.wasm.wheel_zoom_scale(delta_y),
        );
      } else {
        this.wasm.zoom(event.x - pane_left, this.wasm.wheel_zoom_scale(delta_y));
      }
    }
    if (delta_x !== 0) {
      this.wasm.scroll_start(0);
      this.wasm.scroll_move(this.wasm.wheel_scroll_delta(delta_x));
      this.wasm.scroll_end();
    }
    this.render();
  }

  /** Inject the keyboard subset that has deterministic worker semantics. */
  inject_key_event(event: offscreen_key_event): boolean {
    this.assert_live();
    const step = event.ctrl_key || event.shift_key ? 10 : 1;
    const center = this.wasm.time_scale_width() / 2;
    let handled = true;
    switch (event.key) {
      case "ArrowLeft":
        this.wasm.scroll_to_position(this.wasm.scroll_position() - step);
        break;
      case "ArrowRight":
        this.wasm.scroll_to_position(this.wasm.scroll_position() + step);
        break;
      case "+":
      case "=":
        this.wasm.zoom(center, 0.5);
        break;
      case "-":
      case "_":
        this.wasm.zoom(center, -0.5);
        break;
      case "Home":
        this.wasm.fit_content();
        break;
      case "Delete":
      case "Backspace":
        handled = this.wasm.remove_selected_drawing();
        break;
      case "Escape":
        this.wasm.clear_crosshair();
        break;
      default:
        handled = false;
    }
    if (handled) this.render();
    return handled;
  }

  visible_logical_range(): { from: number; to: number } | null {
    this.assert_live();
    const range = this.wasm.visible_logical_range();
    return range.length === 2 ? { from: range[0]!, to: range[1]! } : null;
  }

  frame_stats(): frame_stats {
    this.assert_live();
    const out = this.stats_scratch;
    this.wasm.frame_stats_into(out);
    const gpu_ms = out[FRAME_STATS_SLOT.gpu_ms] as number;
    return {
      cpu_ms: out[FRAME_STATS_SLOT.cpu_ms] as number,
      gpu_ms: Number.isNaN(gpu_ms) ? null : gpu_ms,
      draw_calls: out[FRAME_STATS_SLOT.draw_calls] as number,
      dropped_frames: out[FRAME_STATS_SLOT.dropped_frames] as number,
      presented_frames: out[FRAME_STATS_SLOT.presented_frames] as number,
      memory_bytes: out[FRAME_STATS_SLOT.memory_bytes] as number,
      canvas2d_ops: out[FRAME_STATS_SLOT.canvas2d_ops] as number,
      ring_overruns: out[FRAME_STATS_SLOT.ring_overruns] as number,
    };
  }

  remove(): void {
    if (this.removed) return;
    globalThis.removeEventListener("nucleuscharts-chart-backend-lost", this.backend_loss_handler);
    if (this.drag_pointer_id !== null) this.wasm.scroll_end();
    this.drag_pointer_id = null;
    this.active_pointers.clear();
    this.backend_change_handlers.clear();
    this.removed = true;
    this.wasm.dispose();
    this.wasm.free();
  }

  private assert_live(): void {
    if (this.removed) throw new Error("nucleuscharts: offscreen chart has been removed");
  }
}

/**
 * Construct a worker chart from two transferred canvases. The caller should display only the
 * canvas matching `chart.backend()`; two surfaces preserve runtime Canvas2D fallback without
 * rebuilding chart state.
 */
export async function create_offscreen_chart(
  gpu_canvas: OffscreenCanvas,
  fallback_canvas: OffscreenCanvas,
  init: offscreen_chart_init,
): Promise<offscreen_chart> {
  await ensure_init();
  const width = Math.max(init.width, 1);
  const height = Math.max(init.height, 1);
  const dpr = Math.max(init.dpr, Number.EPSILON);
  const options = init.options ?? {};
  const { theme, engine: engine_options } = split_offscreen_options(options);
  const wasm = await wasm_create_offscreen_chart(
    gpu_canvas,
    fallback_canvas,
    width,
    height,
    dpr,
    options.backend === "canvas2d",
    false,
    init.force_fallback_adapter === true,
  );
  wasm.apply_options(JSON.stringify(theme_options(theme ?? default_theme_name)));
  if (Object.keys(engine_options).length > 0) {
    wasm.apply_options(JSON.stringify(engine_options));
  }
  wasm.set_series_type(KIND_TO_U8[init.series_kind ?? "candlestick"]);
  const chart = new offscreen_chart(wasm, gpu_canvas, fallback_canvas, width, height, dpr);
  chart.render();
  return chart;
}
