// Worker-safe OffscreenCanvas façade. This module deliberately avoids window, document,
// HTMLElement, ResizeObserver, and DOM events; the owning worker relays normalized input samples.

// @ts-ignore -- pkg is generated by build:wasm.
import { create_offscreen_chart as wasm_create_offscreen_chart, NucleusChart } from "../pkg/nucleuscharts_wasm.js";

import { ensure_init, time_to_utc_seconds } from "./impl.js";
import { nucleuscharts_error } from "./errors.js";
import { default_theme_name, theme_options } from "./theme.js";
import { FEATURE_KIND_TO_U8, KIND_TO_U8, is_feature_series_kind } from "./types.js";
import type {
  any_series_options,
  backend_status,
  chart_options,
  deep_partial,
  frame_stats,
  ingestion_diagnostics,
  ohlc_columns,
  series_kind,
  series_data,
} from "./types.js";

const FRAME_STATS_SLOT = {
  cpu_ms: 0,
  gpu_ms: 1,
  draw_calls: 2,
  dropped_frames: 3,
  presented_frames: 4,
  memory_bytes: 5,
  canvas2d_ops: 6,
  ring_overruns: 7,
  gpu_buffer_allocations: 8,
  gpu_write_calls: 9,
  gpu_uploaded_bytes: 10,
  layout_rebuilds: 11,
  autoscale_runs: 12,
  series_rebuilds: 13,
  drawing_rebuilds: 14,
  grid_rebuilds: 15,
  overlay_rebuilds: 16,
  axis_rebuilds: 17,
  text_resolutions: 18,
  trading_rebuilds: 19,
} as const;

const UNSUPPORTED_WORKER_OPTIONS = [
  "autoSize",
  "localization",
  "handle_scroll",
  "handle_scale",
  "kinetic_scroll",
  "tracking_mode",
  "accessibility",
] as const;

type offscreen_layout_options = Omit<deep_partial<chart_options["layout"]>, "panes"> & {
  panes?: Omit<deep_partial<chart_options["layout"]["panes"]>, "enableResize">;
};

/** Engine-owned options supported by a worker chart. DOM gestures, localization callbacks,
 * ResizeObserver sizing, and pane-separator dragging stay on the DOM `create_chart` façade. */
export type offscreen_chart_options = Omit<
  deep_partial<chart_options>,
  (typeof UNSUPPORTED_WORKER_OPTIONS)[number] | "layout"
> & { layout?: offscreen_layout_options };

function split_offscreen_options(options: offscreen_chart_options): {
  theme: "light" | "dark" | undefined;
  wheel_behavior: "auto" | "pan" | "zoom" | undefined;
  engine: Record<string, unknown>;
} {
  const raw = options as Record<string, unknown>;
  for (const key of UNSUPPORTED_WORKER_OPTIONS) {
    if (key in raw) throw new nucleuscharts_error("unsupported_operation", `worker charts do not support option ${key}`);
  }
  const layout = raw.layout as { panes?: Record<string, unknown> } | undefined;
  if (layout?.panes && "enableResize" in layout.panes) {
    throw new nucleuscharts_error(
      "unsupported_operation",
      "worker charts do not support option layout.panes.enableResize",
    );
  }
  const { theme, wheel_behavior, ...engine } = options;
  return { theme, wheel_behavior, engine: engine as Record<string, unknown> };
}

export interface offscreen_chart_init {
  /** Chart media size in CSS pixels. Workers cannot infer this from a transferred canvas. */
  width: number;
  height: number;
  /** Explicit device-pixel ratio used for both backing stores and engine geometry. */
  dpr: number;
  options?: offscreen_chart_options;
  /** Initial kind for the construction-time primary series (default `candlestick`). */
  series_kind?: series_kind;
  /** Test/runtime hook matching the DOM constructor's deterministic fallback path. */
  force_fallback_adapter?: boolean;
}

export interface offscreen_pointer_event {
  type: "down" | "move" | "up" | "cancel" | "leave";
  /** Full-chart media coordinates, not bitmap coordinates. */
  x: number;
  y: number;
  pointer_id?: number;
  button?: number;
  buttons?: number;
  ctrl_key?: boolean;
  meta_key?: boolean;
  shift_key?: boolean;
  pointer_type?: "mouse" | "touch" | "pen";
  timestamp_ms?: number;
  pressure?: number;
  tilt_x?: number;
  tilt_y?: number;
}

export interface offscreen_wheel_event {
  /** Full-chart media coordinates. */
  x: number;
  y: number;
  delta_x: number;
  delta_y: number;
  /** 0 = pixels, 1 = lines, 2 = pages (the WheelEvent values). */
  delta_mode?: 0 | 1 | 2;
  ctrl_key?: boolean;
}

export interface offscreen_key_event {
  key: string;
  ctrl_key?: boolean;
  shift_key?: boolean;
  meta_key?: boolean;
}

/**
 * A chart hosted entirely in a worker. It intentionally exposes the allocation-free typed data
 * path and normalized input injection rather than DOM-only APIs (accessibility, HTML plugins,
 * synchronous screenshots, and ResizeObserver sizing).
 */
export class offscreen_chart {
  private readonly stats_scratch = new Float64Array(NucleusChart.frame_stats_len());
  private readonly input_scratch = new Float64Array(NucleusChart.input_update_len());
  private readonly backend_change_handlers = new Set<(backend: "webgpu" | "canvas2d") => void>();
  private primary_adopted = false;
  private drag_pointer_id: number | null = null;
  private pinch_active = false;
  private last_ingestion: ingestion_diagnostics | null = null;
  private removed = false;
  private width: number;
  private height: number;
  private dpr: number;
  private last_backend: "webgpu" | "canvas2d";
  private readonly backend_loss_handler: EventListener;

  constructor(
    private readonly wasm: NucleusChart,
    private readonly gpu_canvas: OffscreenCanvas,
    private readonly fallback_canvas: OffscreenCanvas,
    width: number,
    height: number,
    dpr: number,
    private wheel_behavior: "auto" | "pan" | "zoom",
  ) {
    this.width = width;
    this.height = height;
    this.dpr = dpr;
    this.last_backend = this.wasm.backend_kind() as "webgpu" | "canvas2d";
    // Device-loss dispatch can occur while a wasm export still owns `NucleusChart`; defer re-entry
    // so wasm-bindgen's recursive-use guard cannot trip.
    this.backend_loss_handler = () => {
      // Rendering performs the actual state transition, then notifies the owner so it can reveal
      // the already-warm fallback HTML canvas.
      queueMicrotask(() => {
        if (!this.removed) this.render();
      });
    };
    globalThis.addEventListener("nucleuscharts-chart-backend-lost", this.backend_loss_handler);
  }

  backend(): "webgpu" | "canvas2d" {
    this.assert_live();
    return this.wasm.backend_kind() as "webgpu" | "canvas2d";
  }

  /** Structured backend selection/fallback diagnostics for this worker chart. */
  backend_status(): Readonly<backend_status> {
    this.assert_live();
    return Object.freeze(JSON.parse(this.wasm.backend_status_json()) as backend_status);
  }

  /** Diagnostics for the most recent worker-side data ingestion. */
  last_ingestion_diagnostics(): ingestion_diagnostics | null {
    this.assert_live();
    return this.last_ingestion;
  }

  private record_ingestion(json: string | undefined): boolean {
    this.last_ingestion = json === undefined ? null : JSON.parse(json) as ingestion_diagnostics;
    return this.last_ingestion?.status !== "rejected";
  }

  /** Subscribe to runtime WebGPU → Canvas2D fallback. The owner should reveal the HTML canvas
   * matching `backend`; returns an unsubscribe function. Construction-time backend is available
   * synchronously from {@link backend}. */
  subscribe_backend_change(handler: (backend: "webgpu" | "canvas2d") => void): () => void {
    this.assert_live();
    this.backend_change_handlers.add(handler);
    return () => this.backend_change_handlers.delete(handler);
  }

  /** Adopt the primary series on the first call; later calls append independent series. */
  add_series(kind: series_kind, options: Partial<any_series_options> = {}): number {
    this.assert_live();
    if (kind === "custom") {
      throw new nucleuscharts_error("unsupported_operation", "custom series need a DOM host renderer");
    }
    if (is_feature_series_kind(kind)) {
      const id = this.wasm.add_feature_series(
        FEATURE_KIND_TO_U8[kind],
        !this.primary_adopted,
        JSON.stringify(options),
      );
      this.primary_adopted = true;
      if (id === 0xffffffff) {
        throw new nucleuscharts_error("invalid_options", `advanced series '${kind}' was rejected by the engine`);
      }
      this.render();
      return id;
    }
    if (!this.primary_adopted) {
      this.primary_adopted = true;
      this.wasm.set_series_type(KIND_TO_U8[kind]);
      this.render();
      return 0;
    }
    const id = this.wasm.add_series(KIND_TO_U8[kind]);
    this.render();
    return id;
  }

  set_data_typed(columns: ohlc_columns, series_id = 0): void {
    this.assert_live();
    if (this.wasm.series_kind(series_id) === 7) {
      throw new nucleuscharts_error(
        "unsupported_operation",
        "set_data_typed() does not apply to structured advanced-series payloads",
      );
    }
    if (!this.record_ingestion(this.wasm.set_series_data_typed(
      series_id, columns.times, columns.open, columns.high, columns.low, columns.close,
    ))) return;
    this.render();
  }

  update_typed(columns: ohlc_columns, series_id = 0): void {
    this.assert_live();
    if (this.wasm.series_kind(series_id) === 7) {
      throw new nucleuscharts_error(
        "unsupported_operation",
        "update_typed() does not apply to structured advanced-series payloads",
      );
    }
    if (!this.record_ingestion(this.wasm.update_series_bars_typed(
      series_id, columns.times, columns.open, columns.high, columns.low, columns.close,
    ))) return;
    this.render();
  }

  /** Replace structured data for a Rust-native advanced series in a worker chart. */
  set_feature_data(data: readonly series_data[], series_id = 0): void {
    this.assert_live();
    const converted = data.map((item) => ({ ...item, time: time_to_utc_seconds(item.time) }));
    if (!this.record_ingestion(this.wasm.set_feature_series_data(series_id, converted))) return;
    this.render();
  }

  /** Append or replace one structured advanced-series row in a worker chart. */
  update_feature(item: series_data, series_id = 0): void {
    this.assert_live();
    if (!this.record_ingestion(this.wasm.update_feature_series_item(
      series_id,
      { ...item, time: time_to_utc_seconds(item.time) },
    ))) return;
    this.render();
  }

  apply_options(options: offscreen_chart_options): void {
    this.assert_live();
    const { theme, wheel_behavior, engine } = split_offscreen_options(options);
    if (wheel_behavior !== undefined) this.wheel_behavior = wheel_behavior;
    if (theme !== undefined) this.wasm.apply_options(JSON.stringify(theme_options(theme)));
    if (Object.keys(engine).length > 0) this.wasm.apply_options(JSON.stringify(engine));
    this.render();
  }

  fit_content(): void {
    this.assert_live();
    this.wasm.fit_content();
    this.render();
  }

  resize(width: number, height: number, dpr = this.dpr): void {
    this.assert_live();
    this.width = Math.max(width, 1);
    this.height = Math.max(height, 1);
    this.dpr = Math.max(dpr, Number.EPSILON);
    const bitmap_width = Math.max(1, Math.round(this.width * this.dpr));
    const bitmap_height = Math.max(1, Math.round(this.height * this.dpr));
    this.gpu_canvas.width = bitmap_width;
    this.gpu_canvas.height = bitmap_height;
    this.fallback_canvas.width = bitmap_width;
    this.fallback_canvas.height = bitmap_height;
    this.wasm.resize(this.width, this.height, this.dpr);
    this.render();
  }

  render(): void {
    this.assert_live();
    this.wasm.render();
    const backend = this.backend();
    if (backend !== this.last_backend) {
      this.last_backend = backend;
      for (const handler of this.backend_change_handlers) {
        try {
          handler(backend);
        } catch (error) {
          console.error("nucleuscharts: offscreen backend-change handler threw", error);
        }
      }
    }
  }

  /**
   * Inject a normalized pointer sample relayed from the host. Primary-pointer drags pan the time
   * scale; hover/move drives the crosshair. Axis coordinates are accepted but do not begin a pan.
   */
  inject_pointer_event(event: offscreen_pointer_event): void {
    this.assert_live();
    const id = event.pointer_id ?? 1;
    const x = event.x - this.wasm.pane_left();
    const y = event.y;
    const pane_width = this.wasm.time_scale_width();
    const pane_height = this.height - this.wasm.time_scale_height();
    const in_pane = x >= 0 && x <= pane_width && y >= 0 && y <= pane_height;
    const primary = (event.button ?? 0) === 0;
    const device = event.pointer_type === "touch" ? 1 : event.pointer_type === "pen" ? 2 : 0;
    const target = in_pane ? 0 : y > pane_height ? 4 : 3;
    const feed = (phase: "down" | "move" | "up") => {
      const method = phase === "down" ? this.wasm.input_pointer_down.bind(this.wasm)
        : phase === "move" ? this.wasm.input_pointer_move.bind(this.wasm)
          : this.wasm.input_pointer_up.bind(this.wasm);
      const modifiers = (event.shift_key ? 1 : 0) | (event.ctrl_key ? 2 : 0)
        | (event.meta_key ? 8 : 0);
      method(
        id, device, target, modifiers, x, y, event.timestamp_ms ?? performance.now(),
        event.pressure ?? (primary ? 0.5 : 0), event.tilt_x ?? 0, event.tilt_y ?? 0,
        this.input_scratch,
      );
      return {
        kind: this.input_scratch[0]!,
        pointer_id: this.input_scratch[2]!,
        x: this.input_scratch[5]!,
        y: this.input_scratch[6]!,
        previous_x: this.input_scratch[7]!,
        scale_delta: this.input_scratch[9]!,
      };
    };

    switch (event.type) {
      case "down":
        if (!primary) return;
        {
          const update = feed("down");
          if (update.kind === 11) return;
          if (update.kind === 5) {
            if (this.drag_pointer_id !== null) this.wasm.scroll_end();
            this.drag_pointer_id = null;
            this.pinch_active = true;
            this.wasm.scroll_start(update.x);
          } else if (in_pane && this.drag_pointer_id === null) {
            this.wasm.scroll_start(x);
            this.drag_pointer_id = id;
            this.wasm.set_crosshair(x, y);
          }
        }
        break;
      case "move":
        {
          const update = feed("move");
          if (update.kind === 6) {
            this.wasm.scroll_move(update.x);
            if (update.scale_delta !== 0) {
              this.wasm.zoom(update.x, this.wasm.pinch_zoom_scale(update.scale_delta));
            }
          } else if (this.drag_pointer_id === id) {
            this.wasm.scroll_move(x);
          }
        }
        if (in_pane || this.drag_pointer_id === id) this.wasm.set_crosshair(x, y);
        else this.wasm.clear_crosshair();
        break;
      case "up": {
        const update = feed("up");
        if (update.kind === 7) {
          this.wasm.scroll_end();
          this.wasm.scroll_start(update.x);
          this.drag_pointer_id = update.pointer_id;
          this.pinch_active = false;
        } else if (this.drag_pointer_id === id || this.pinch_active) {
          this.wasm.scroll_end();
          this.drag_pointer_id = null;
          this.pinch_active = false;
        }
        break;
      }
      case "cancel":
        this.wasm.input_cancel_all(this.input_scratch);
        if (this.drag_pointer_id !== null || this.pinch_active) this.wasm.scroll_end();
        this.drag_pointer_id = null;
        this.pinch_active = false;
        break;
      case "leave":
        if (this.drag_pointer_id !== id) this.wasm.clear_crosshair();
        break;
    }
    this.render();
  }

  /** Inject a relayed wheel sample using the DOM recognizer's delta normalization. */
  inject_wheel_event(event: offscreen_wheel_event): void {
    this.assert_live();
    const adjustment = event.delta_mode === 2 ? 120 : event.delta_mode === 1 ? 32 : 1;
    const delta_x = (adjustment * event.delta_x) / 100;
    const delta_y = -(adjustment * event.delta_y) / 100;
    const pane_left = this.wasm.pane_left();
    const behavior = this.wheel_behavior === "pan" ? 1 : this.wheel_behavior === "zoom" ? 2 : 0;
    const intent = this.wasm.classify_wheel(
      behavior, delta_x, delta_y, event.delta_mode ?? 0, event.ctrl_key === true,
    );
    const pan_delta = this.wheel_behavior === "auto"
      ? delta_x : Math.abs(delta_x) >= Math.abs(delta_y) ? delta_x : -delta_y;
    if ((intent & 2) !== 0 && delta_y !== 0) {
      const pane = this.wasm.pane_index_at_y(event.y);
      const target = this.wasm.price_axis_target_at(pane, event.x - pane_left) ?? null;
      if (target !== null) {
        this.wasm.price_axis_wheel_zoom(
          pane,
          target,
          event.y,
          this.wasm.wheel_zoom_scale(delta_y),
        );
      } else {
        this.wasm.zoom(event.x - pane_left, this.wasm.wheel_zoom_scale(delta_y));
      }
    }
    if ((intent & 1) !== 0 && pan_delta !== 0) {
      this.wasm.scroll_start(0);
      this.wasm.scroll_move(this.wasm.wheel_scroll_delta(pan_delta));
      this.wasm.scroll_end();
    }
    this.render();
  }

  /** Inject the keyboard subset that has deterministic worker semantics. */
  inject_key_event(event: offscreen_key_event): boolean {
    this.assert_live();
    const step = event.ctrl_key || event.shift_key ? 10 : 1;
    const center = this.wasm.time_scale_width() / 2;
    let handled = true;
    switch (event.key) {
      case "ArrowLeft":
        this.wasm.scroll_to_position(this.wasm.scroll_position() - step);
        break;
      case "ArrowRight":
        this.wasm.scroll_to_position(this.wasm.scroll_position() + step);
        break;
      case "+":
      case "=":
        this.wasm.zoom(center, 0.5);
        break;
      case "-":
      case "_":
        this.wasm.zoom(center, -0.5);
        break;
      case "Home":
        this.wasm.fit_content();
        break;
      case "Delete":
      case "Backspace":
        handled = this.wasm.remove_selected_drawing();
        break;
      case "Escape":
        this.wasm.clear_crosshair();
        break;
      default:
        handled = false;
    }
    if (handled) this.render();
    return handled;
  }

  visible_logical_range(): { from: number; to: number } | null {
    this.assert_live();
    const range = this.wasm.visible_logical_range();
    return range.length === 2 ? { from: range[0]!, to: range[1]! } : null;
  }

  frame_stats(): frame_stats {
    this.assert_live();
    const out = this.stats_scratch;
    this.wasm.frame_stats_into(out);
    const gpu_ms = out[FRAME_STATS_SLOT.gpu_ms] as number;
    return {
      cpu_ms: out[FRAME_STATS_SLOT.cpu_ms] as number,
      gpu_ms: Number.isNaN(gpu_ms) ? null : gpu_ms,
      draw_calls: out[FRAME_STATS_SLOT.draw_calls] as number,
      dropped_frames: out[FRAME_STATS_SLOT.dropped_frames] as number,
      presented_frames: out[FRAME_STATS_SLOT.presented_frames] as number,
      memory_bytes: out[FRAME_STATS_SLOT.memory_bytes] as number,
      canvas2d_ops: out[FRAME_STATS_SLOT.canvas2d_ops] as number,
      ring_overruns: out[FRAME_STATS_SLOT.ring_overruns] as number,
      gpu_buffer_allocations: out[FRAME_STATS_SLOT.gpu_buffer_allocations] as number,
      gpu_write_calls: out[FRAME_STATS_SLOT.gpu_write_calls] as number,
      gpu_uploaded_bytes: out[FRAME_STATS_SLOT.gpu_uploaded_bytes] as number,
      layout_rebuilds: out[FRAME_STATS_SLOT.layout_rebuilds] as number,
      autoscale_runs: out[FRAME_STATS_SLOT.autoscale_runs] as number,
      series_rebuilds: out[FRAME_STATS_SLOT.series_rebuilds] as number,
      drawing_rebuilds: out[FRAME_STATS_SLOT.drawing_rebuilds] as number,
      grid_rebuilds: out[FRAME_STATS_SLOT.grid_rebuilds] as number,
      overlay_rebuilds: out[FRAME_STATS_SLOT.overlay_rebuilds] as number,
      axis_rebuilds: out[FRAME_STATS_SLOT.axis_rebuilds] as number,
      text_resolutions: out[FRAME_STATS_SLOT.text_resolutions] as number,
      trading_rebuilds: out[FRAME_STATS_SLOT.trading_rebuilds] as number,
    };
  }

  remove(): void {
    if (this.removed) return;
    globalThis.removeEventListener("nucleuscharts-chart-backend-lost", this.backend_loss_handler);
    if (this.drag_pointer_id !== null) this.wasm.scroll_end();
    this.wasm.input_cancel_all(this.input_scratch);
    this.drag_pointer_id = null;
    this.pinch_active = false;
    this.backend_change_handlers.clear();
    this.removed = true;
    this.wasm.dispose();
    this.wasm.free();
  }

  private assert_live(): void {
    if (this.removed) throw new nucleuscharts_error("disposed", "offscreen chart has been removed");
  }
}

/**
 * Construct a worker chart from two transferred canvases. The caller should display only the
 * canvas matching `chart.backend()`; two surfaces preserve runtime Canvas2D fallback without
 * rebuilding chart state.
 */
/** @experimental Worker/offscreen hosting is not part of the frozen stable surface. */
export async function create_offscreen_chart(
  gpu_canvas: OffscreenCanvas,
  fallback_canvas: OffscreenCanvas,
  init: offscreen_chart_init,
): Promise<offscreen_chart> {
  await ensure_init();
  const width = Math.max(init.width, 1);
  const height = Math.max(init.height, 1);
  const dpr = Math.max(init.dpr, Number.EPSILON);
  const options = init.options ?? {};
  const { theme, wheel_behavior, engine: engine_options } = split_offscreen_options(options);
  const wasm = await wasm_create_offscreen_chart(
    gpu_canvas,
    fallback_canvas,
    width,
    height,
    dpr,
    options.backend === "canvas2d",
    false,
    init.force_fallback_adapter === true,
  );
  wasm.apply_options(JSON.stringify(theme_options(theme ?? default_theme_name)));
  if (Object.keys(engine_options).length > 0) {
    wasm.apply_options(JSON.stringify(engine_options));
  }
  wasm.set_series_type(KIND_TO_U8[init.series_kind ?? "candlestick"]);
  const chart = new offscreen_chart(
    wasm, gpu_canvas, fallback_canvas, width, height, dpr, wheel_behavior ?? "auto",
  );
  chart.render();
  return chart;
}
