// Worker-safe OffscreenCanvas façade. This module deliberately avoids window, document,
// HTMLElement, ResizeObserver, and DOM events; the owning worker relays normalized input samples.

// @ts-ignore -- pkg is generated by build:wasm.
import { create_offscreen_chart as wasm_create_offscreen_chart, AerisChart } from "../pkg/aeris_charts_wasm.js";

import { ensure_init, time_to_utc_seconds } from "./impl.js";
import { controller_pointer_flags } from "./gestures.js";
import { AerisChartsError } from "./errors.js";
import { default_theme_name, theme_options, theme_palette, type theme_name } from "./theme.js";
import { FEATURE_KIND_TO_U8, KIND_TO_U8, is_feature_series_kind, is_footprint_series_kind } from "./types.js";
import type {
  any_series_options,
  backend_status,
  chart_options,
  deep_partial,
  frame_stats,
  footprint_bar,
  footprint_trade,
  footprint_trade_columns,
  ingestion_diagnostics,
  ohlc_columns,
  series_kind,
  series_data,
} from "./types.js";

const FRAME_STATS_SLOT = {
  cpu_ms: 0,
  gpu_ms: 1,
  draw_calls: 2,
  dropped_frames: 3,
  presented_frames: 4,
  memory_bytes: 5,
  canvas2d_ops: 6,
  ring_overruns: 7,
  gpu_buffer_allocations: 8,
  gpu_write_calls: 9,
  gpu_uploaded_bytes: 10,
  layout_rebuilds: 11,
  autoscale_runs: 12,
  series_rebuilds: 13,
  drawing_rebuilds: 14,
  grid_rebuilds: 15,
  overlay_rebuilds: 16,
  axis_rebuilds: 17,
  text_resolutions: 18,
  trading_rebuilds: 19,
} as const;

const UNSUPPORTED_WORKER_OPTIONS = [
  "autoSize",
  "localization",
  "handle_scroll",
  "handle_scale",
  "kinetic_scroll",
  "tracking_mode",
  "accessibility",
] as const;

type offscreen_layout_options = Omit<deep_partial<chart_options["layout"]>, "panes"> & {
  panes?: Omit<deep_partial<chart_options["layout"]["panes"]>, "enableResize">;
};

/** Engine-owned options supported by a worker chart. DOM gestures, localization callbacks,
 * ResizeObserver sizing, and pane-separator dragging stay on the DOM `create_chart` façade. */
export type offscreen_chart_options = Omit<
  deep_partial<chart_options>,
  (typeof UNSUPPORTED_WORKER_OPTIONS)[number] | "layout"
> & { layout?: offscreen_layout_options };

function split_offscreen_options(options: offscreen_chart_options): {
  theme: "light" | "dark" | undefined;
  wheel_behavior: "auto" | "pan" | "zoom" | undefined;
  price_axis_wheel_zoom: boolean | undefined;
  engine: Record<string, unknown>;
} {
  const raw = options as Record<string, unknown>;
  for (const key of UNSUPPORTED_WORKER_OPTIONS) {
    if (key in raw) throw new AerisChartsError("unsupported_operation", `worker charts do not support option ${key}`);
  }
  const layout = raw.layout as { panes?: Record<string, unknown> } | undefined;
  if (layout?.panes && "enableResize" in layout.panes) {
    throw new AerisChartsError(
      "unsupported_operation",
      "worker charts do not support option layout.panes.enableResize",
    );
  }
  const { theme, wheel_behavior, price_axis_wheel_zoom, ...engine } = options;
  return { theme, wheel_behavior, price_axis_wheel_zoom, engine: engine as Record<string, unknown> };
}

export interface offscreen_chart_init {
  /** Chart media size in CSS pixels. Workers cannot infer this from a transferred canvas. */
  width: number;
  height: number;
  /** Explicit device-pixel ratio used for both backing stores and engine geometry. */
  dpr: number;
  options?: offscreen_chart_options;
  /** Initial kind for the construction-time primary series (default `candlestick`). */
  series_kind?: series_kind;
  /** Test/runtime hook matching the DOM constructor's deterministic fallback path. */
  force_fallback_adapter?: boolean;
}

export interface offscreen_pointer_event {
  type: "down" | "move" | "up" | "cancel" | "leave";
  /** Full-chart media coordinates, not bitmap coordinates. */
  x: number;
  y: number;
  pointer_id?: number;
  click_count?: number;
  button?: number;
  buttons?: number;
  ctrl_key?: boolean;
  meta_key?: boolean;
  shift_key?: boolean;
  alt_key?: boolean;
  pointer_type?: "mouse" | "touch" | "pen";
  timestamp_ms?: number;
  pressure?: number;
  tilt_x?: number;
  tilt_y?: number;
}

export interface offscreen_wheel_event {
  /** Full-chart media coordinates. */
  x: number;
  y: number;
  delta_x: number;
  delta_y: number;
  /** 0 = pixels, 1 = lines, 2 = pages (the WheelEvent values). */
  delta_mode?: 0 | 1 | 2;
  /** Pixel-mode raw delta unit, in device pixels per CSS pixel; omit for CSS-pixel events. */
  pixel_ratio?: number;
  /** Ctrl (or `meta_key`, macOS Cmd) zooms around the pointer instead of pinning the right edge. */
  ctrl_key?: boolean;
  shift_key?: boolean;
  meta_key?: boolean;
}

export interface offscreen_key_event {
  key: string;
  /** Omit for a discrete press; use down/up for a held key. */
  type?: "press" | "down" | "up";
  ctrl_key?: boolean;
  shift_key?: boolean;
  alt_key?: boolean;
  meta_key?: boolean;
  repeat?: boolean;
  timestamp_ms?: number;
  reduced_motion?: boolean;
}

/**
 * A chart hosted entirely in a worker. It intentionally exposes the allocation-free typed data
 * path and normalized input injection rather than DOM-only APIs (accessibility, HTML plugins,
 * synchronous screenshots, and ResizeObserver sizing).
 */
export class offscreen_chart {
  private readonly stats_scratch = new Float64Array(AerisChart.frame_stats_len());
  private readonly backend_change_handlers = new Set<(backend: "webgpu" | "canvas2d") => void>();
  private primary_adopted = false;
  private last_ingestion: ingestion_diagnostics | null = null;
  private removed = false;
  private input_timer: ReturnType<typeof setTimeout> | null = null;
  private width: number;
  private height: number;
  private dpr: number;
  private last_backend: "webgpu" | "canvas2d";
  private readonly backend_loss_handler: EventListener;

  constructor(
    private readonly wasm: AerisChart,
    private readonly gpu_canvas: OffscreenCanvas,
    private readonly fallback_canvas: OffscreenCanvas,
    width: number,
    height: number,
    dpr: number,
    private wheel_behavior: "auto" | "pan" | "zoom",
    private price_axis_wheel_zoom: boolean,
    private selected_theme: theme_name = default_theme_name,
  ) {
    this.width = width;
    this.height = height;
    this.dpr = dpr;
    this.last_backend = this.wasm.backend_kind() as "webgpu" | "canvas2d";
    // Device-loss dispatch can occur while a wasm export still owns `AerisChart`; defer re-entry
    // so wasm-bindgen's recursive-use guard cannot trip.
    this.backend_loss_handler = () => {
      // Rendering performs the actual state transition, then notifies the owner so it can reveal
      // the already-warm fallback HTML canvas.
      queueMicrotask(() => {
        if (!this.removed) this.render();
      });
    };
    globalThis.addEventListener("aeris_charts-chart-backend-lost", this.backend_loss_handler);
  }

  backend(): "webgpu" | "canvas2d" {
    this.assert_live();
    return this.wasm.backend_kind() as "webgpu" | "canvas2d";
  }

  /** Structured backend selection/fallback diagnostics for this worker chart. */
  backend_status(): Readonly<backend_status> {
    this.assert_live();
    return Object.freeze(JSON.parse(this.wasm.backend_status_json()) as backend_status);
  }

  /** Diagnostics for the most recent worker-side data ingestion. */
  last_ingestion_diagnostics(): ingestion_diagnostics | null {
    this.assert_live();
    return this.last_ingestion;
  }

  private record_ingestion(json: string | undefined): boolean {
    this.last_ingestion = json === undefined ? null : JSON.parse(json) as ingestion_diagnostics;
    return this.last_ingestion?.status !== "rejected";
  }

  /** Subscribe to runtime WebGPU → Canvas2D fallback. The owner should reveal the HTML canvas
   * matching `backend`; returns an unsubscribe function. Construction-time backend is available
   * synchronously from {@link backend}. */
  subscribe_backend_change(handler: (backend: "webgpu" | "canvas2d") => void): () => void {
    this.assert_live();
    this.backend_change_handlers.add(handler);
    return () => this.backend_change_handlers.delete(handler);
  }

  /** Adopt the primary series on the first call; later calls append independent series. */
  add_series(kind: series_kind, options: Partial<any_series_options> = {}): number {
    this.assert_live();
    if (kind === "custom") {
      throw new AerisChartsError("unsupported_operation", "custom series need a DOM host renderer");
    }
    if (is_footprint_series_kind(kind)) {
      const id = this.wasm.add_footprint_series(!this.primary_adopted, JSON.stringify(options));
      this.primary_adopted = true;
      if (id === 0xffffffff) {
        throw new AerisChartsError("invalid_options", "footprint series options were rejected by the engine");
      }
      this.render();
      return id;
    }
    if (is_feature_series_kind(kind)) {
      const id = this.wasm.add_feature_series(
        FEATURE_KIND_TO_U8[kind],
        !this.primary_adopted,
        JSON.stringify(options),
      );
      this.primary_adopted = true;
      if (id === 0xffffffff) {
        throw new AerisChartsError("invalid_options", `advanced series '${kind}' was rejected by the engine`);
      }
      this.render();
      return id;
    }
    if (!this.primary_adopted) {
      this.primary_adopted = true;
      this.wasm.set_series_type(KIND_TO_U8[kind]);
      this.render();
      return 0;
    }
    const id = this.wasm.add_series(KIND_TO_U8[kind]);
    this.render();
    return id;
  }

  set_data_typed(columns: ohlc_columns, series_id = 0): void {
    this.assert_live();
    if (this.wasm.series_kind(series_id) === 7 || this.wasm.series_kind(series_id) === 8) {
      throw new AerisChartsError(
        "unsupported_operation",
        "set_data_typed() does not apply to structured advanced-series payloads",
      );
    }
    if (!this.record_ingestion(this.wasm.set_series_data_typed(
      series_id, columns.times, columns.open, columns.high, columns.low, columns.close,
    ))) return;
    this.render();
  }

  update_typed(columns: ohlc_columns, series_id = 0): void {
    this.assert_live();
    if (this.wasm.series_kind(series_id) === 7 || this.wasm.series_kind(series_id) === 8) {
      throw new AerisChartsError(
        "unsupported_operation",
        "update_typed() does not apply to structured advanced-series payloads",
      );
    }
    if (!this.record_ingestion(this.wasm.update_series_bars_typed(
      series_id, columns.times, columns.open, columns.high, columns.low, columns.close,
    ))) return;
    this.render();
  }

  /** Replace structured data for a Rust-native advanced series in a worker chart. */
  set_feature_data(data: readonly series_data[], series_id = 0): void {
    this.assert_live();
    const converted = data.map((item) => ({ ...item, time: time_to_utc_seconds(item.time) }));
    if (!this.record_ingestion(this.wasm.set_feature_series_data(series_id, converted))) return;
    this.render();
  }

  /** Append or replace one structured advanced-series row in a worker chart. */
  update_feature(item: series_data, series_id = 0): void {
    this.assert_live();
    if (!this.record_ingestion(this.wasm.update_feature_series_item(
      series_id,
      { ...item, time: time_to_utc_seconds(item.time) },
    ))) return;
    this.render();
  }

  set_footprint_trades_typed(columns: footprint_trade_columns, series_id = 0): void {
    this.assert_live();
    const result = this.wasm.set_footprint_trades_typed(
      series_id,
      columns.timestamps_micros,
      columns.prices,
      columns.volumes,
      columns.aggressors,
      columns.bids,
      columns.asks,
      columns.sequences,
      columns.trade_ids,
      columns.conditions,
      columns.session_ids,
    );
    if (result !== "") throw new AerisChartsError("invalid_data", result);
    this.render();
  }

  update_footprint_trades_typed(
    columns: footprint_trade_columns,
    series_id = 0,
  ): "tip" | "historical" {
    this.assert_live();
    const result = this.wasm.update_footprint_trades_typed(
      series_id,
      columns.timestamps_micros,
      columns.prices,
      columns.volumes,
      columns.aggressors,
      columns.bids,
      columns.asks,
      columns.sequences,
      columns.trade_ids,
      columns.conditions,
      columns.session_ids,
    );
    if (result !== "tip" && result !== "historical") {
      throw new AerisChartsError("invalid_data", result);
    }
    this.render();
    return result;
  }

  update_footprint_trade(trade: footprint_trade, series_id = 0): "tip" | "historical" {
    this.assert_live();
    const side = trade.aggressor === "buy" ? 1 : trade.aggressor === "sell" ? 2 : 0;
    const result = this.wasm.update_footprint_trade_typed(
      series_id,
      trade.timestamp_micros,
      trade.price,
      trade.volume,
      side,
      trade.bid ?? Number.NaN,
      trade.ask ?? Number.NaN,
      trade.sequence ?? Number.NaN,
      trade.trade_id ?? Number.NaN,
      trade.conditions ?? 0,
      trade.session_id ?? Number.NaN,
    );
    if (result !== "tip" && result !== "historical") {
      throw new AerisChartsError("invalid_data", result);
    }
    this.render();
    return result;
  }

  footprint_bars(series_id = 0): readonly footprint_bar[] {
    this.assert_live();
    return JSON.parse(this.wasm.footprint_bars_json(series_id)) as footprint_bar[];
  }

  apply_options(options: offscreen_chart_options): void {
    this.assert_live();
    const { theme, wheel_behavior, price_axis_wheel_zoom, engine } = split_offscreen_options(options);
    if (wheel_behavior !== undefined) this.wheel_behavior = wheel_behavior;
    if (price_axis_wheel_zoom !== undefined) this.price_axis_wheel_zoom = price_axis_wheel_zoom;
    if (theme !== undefined) {
      this.selected_theme = theme;
      this.wasm.apply_options(JSON.stringify(theme_options(theme_palette(theme))));
    }
    if (Object.keys(engine).length > 0) this.wasm.apply_options(JSON.stringify(engine));
    this.render();
  }

  /** Restore canonical Aeris visual defaults for the currently selected theme without resetting
   * data, scale/view state, or advanced-series semantics. */
  reset_style_to_defaults(): void {
    this.assert_live();
    this.wasm.reset_style_to_defaults(this.selected_theme === "light");
    this.render();
  }

  fit_content(): void {
    this.assert_live();
    this.wasm.fit_content();
    this.render();
  }

  resize(width: number, height: number, dpr = this.dpr): void {
    this.assert_live();
    this.width = Math.max(width, 1);
    this.height = Math.max(height, 1);
    this.dpr = Math.max(dpr, Number.EPSILON);
    const bitmap_width = Math.max(1, Math.round(this.width * this.dpr));
    const bitmap_height = Math.max(1, Math.round(this.height * this.dpr));
    this.gpu_canvas.width = bitmap_width;
    this.gpu_canvas.height = bitmap_height;
    this.fallback_canvas.width = bitmap_width;
    this.fallback_canvas.height = bitmap_height;
    this.wasm.resize(this.width, this.height, this.dpr);
    this.render();
  }

  render(): void {
    this.assert_live();
    this.wasm.controller_flush_coalesced_input();
    this.wasm.render();
    const backend = this.backend();
    if (backend !== this.last_backend) {
      this.last_backend = backend;
      for (const handler of this.backend_change_handlers) {
        try {
          handler(backend);
        } catch (error) {
          console.error("aeris_charts: offscreen backend-change handler threw", error);
        }
      }
    }
  }

  /**
   * Inject a normalized pointer sample relayed from the host. Primary-pointer drags pan the time
   * scale; hover/move drives the crosshair. Axis coordinates are accepted but do not begin a pan.
   */
  inject_pointer_event(event: offscreen_pointer_event): void {
    this.assert_live();
    const id = event.pointer_id ?? 1;
    const x = event.x - this.wasm.pane_left();
    const y = event.y;
    const primary = (event.button ?? 0) === 0;
    const device = event.pointer_type === "touch" ? 1 : event.pointer_type === "pen" ? 2 : 0;
    const modifiers = (event.shift_key ? 1 : 0) | (event.ctrl_key ? 2 : 0)
      | (event.alt_key ? 4 : 0) | (event.meta_key ? 8 : 0);
    const timestamp = event.timestamp_ms ?? performance.now();
    // Default worker policy matches the controller's mouse and touch interaction defaults.
    const options = 0b111_1100_1111;
    const flags = controller_pointer_flags(device, modifiers, options);
    switch (event.type) {
      case "down":
        if (!primary) return;
        this.wasm.controller_pointer_down(id, x, y, timestamp, event.click_count ?? 1, flags);
        break;
      case "move":
        if (event.buttons !== undefined && event.buttons !== 0 && (event.buttons & 1) === 0) return;
        this.wasm.controller_pointer_move(id, x, y, timestamp,
          ((event.buttons ?? (device === 1 ? 1 : 0)) & 1) !== 0, flags);
        break;
      case "up":
        if (!primary) return;
        this.wasm.controller_pointer_up(id, x, y, timestamp, flags);
        break;
      case "cancel":
        this.wasm.controller_pointer_cancel_id(id);
        break;
      case "leave":
        this.wasm.controller_pointer_leave();
        break;
    }
    this.consume_input_events();
    this.render();
    this.schedule_input_tick();
  }

  /** Inject a relayed wheel sample using the DOM recognizer's delta normalization. */
  inject_wheel_event(event: offscreen_wheel_event): void {
    this.assert_live();
    const behavior = this.wheel_behavior === "pan" ? 1 : this.wheel_behavior === "zoom" ? 2 : 0;
    const modifiers = (event.shift_key ? 1 : 0) | (event.ctrl_key ? 2 : 0)
      | (event.meta_key ? 8 : 0);
    if (this.wasm.input_wheel(
      event.x - this.wasm.pane_left(),
      event.y,
      event.delta_x,
      event.delta_y,
      event.delta_mode ?? 0,
      event.pixel_ratio ?? 1,
      modifiers,
      behavior,
      true,
      true,
      this.price_axis_wheel_zoom,
      performance.now(),
    )) this.render();
  }

  /** Route a worker key sample through the same controller used by browser and GPUI hosts. */
  inject_key_event(event: offscreen_key_event): boolean {
    this.assert_live();
    const modifiers = (event.shift_key ? 1 : 0) | (event.ctrl_key ? 2 : 0)
      | (event.alt_key ? 4 : 0) | (event.meta_key ? 8 : 0);
    const handled = event.type === "up"
      ? this.wasm.input_key_up(event.key, modifiers)
      : this.wasm.input_key_down(event.key, modifiers, event.repeat ?? false,
        event.timestamp_ms ?? performance.now(),
        event.type === "down" ? event.reduced_motion ?? false : true, true);
    if (handled) this.consume_input_events();
    if (handled) this.render();
    if (this.wasm.input_animating()) this.schedule_input_tick();
    return handled;
  }

  private consume_input_events(): void {
    const events = JSON.parse(this.wasm.take_input_events_json()) as Array<
      { kind: string; id?: number }
    >;
    for (const event of events) {
      if (event.kind !== "remove_series" || event.id === undefined) continue;
      if (this.wasm.remove_series_tracked(event.id).length > 0 && event.id === 0) {
        this.primary_adopted = true;
      }
    }
  }

  private schedule_input_tick(): void {
    if (this.input_timer !== null) return;
    const deadline = this.wasm.input_wake_deadline_ms();
    const animating = this.wasm.input_animating();
    if (!animating && (deadline === undefined || !Number.isFinite(deadline))) return;
    const delay = animating ? 16 : Math.max(0, deadline! - performance.now());
    this.input_timer = setTimeout(() => {
      this.input_timer = null;
      if (this.removed) return;
      if (this.wasm.input_tick(performance.now())) this.render();
      this.schedule_input_tick();
    }, delay);
  }

  visible_logical_range(): { from: number; to: number } | null {
    this.assert_live();
    const range = this.wasm.visible_logical_range();
    return range.length === 2 ? { from: range[0]!, to: range[1]! } : null;
  }

  frame_stats(): frame_stats {
    this.assert_live();
    const out = this.stats_scratch;
    this.wasm.frame_stats_into(out);
    const gpu_ms = out[FRAME_STATS_SLOT.gpu_ms] as number;
    return {
      cpu_ms: out[FRAME_STATS_SLOT.cpu_ms] as number,
      gpu_ms: Number.isNaN(gpu_ms) ? null : gpu_ms,
      draw_calls: out[FRAME_STATS_SLOT.draw_calls] as number,
      dropped_frames: out[FRAME_STATS_SLOT.dropped_frames] as number,
      presented_frames: out[FRAME_STATS_SLOT.presented_frames] as number,
      memory_bytes: out[FRAME_STATS_SLOT.memory_bytes] as number,
      canvas2d_ops: out[FRAME_STATS_SLOT.canvas2d_ops] as number,
      ring_overruns: out[FRAME_STATS_SLOT.ring_overruns] as number,
      gpu_buffer_allocations: out[FRAME_STATS_SLOT.gpu_buffer_allocations] as number,
      gpu_write_calls: out[FRAME_STATS_SLOT.gpu_write_calls] as number,
      gpu_uploaded_bytes: out[FRAME_STATS_SLOT.gpu_uploaded_bytes] as number,
      layout_rebuilds: out[FRAME_STATS_SLOT.layout_rebuilds] as number,
      autoscale_runs: out[FRAME_STATS_SLOT.autoscale_runs] as number,
      series_rebuilds: out[FRAME_STATS_SLOT.series_rebuilds] as number,
      drawing_rebuilds: out[FRAME_STATS_SLOT.drawing_rebuilds] as number,
      grid_rebuilds: out[FRAME_STATS_SLOT.grid_rebuilds] as number,
      overlay_rebuilds: out[FRAME_STATS_SLOT.overlay_rebuilds] as number,
      axis_rebuilds: out[FRAME_STATS_SLOT.axis_rebuilds] as number,
      text_resolutions: out[FRAME_STATS_SLOT.text_resolutions] as number,
      trading_rebuilds: out[FRAME_STATS_SLOT.trading_rebuilds] as number,
    };
  }

  remove(): void {
    if (this.removed) return;
    if (this.input_timer !== null) clearTimeout(this.input_timer);
    this.input_timer = null;
    globalThis.removeEventListener("aeris_charts-chart-backend-lost", this.backend_loss_handler);
    this.wasm.controller_pointer_cancel();
    this.backend_change_handlers.clear();
    this.removed = true;
    this.wasm.dispose();
    this.wasm.free();
  }

  private assert_live(): void {
    if (this.removed) throw new AerisChartsError("disposed", "offscreen chart has been removed");
  }
}

/**
 * Construct a worker chart from two transferred canvases. The caller should display only the
 * canvas matching `chart.backend()`; two surfaces preserve runtime Canvas2D fallback without
 * rebuilding chart state.
 */
/** @experimental Worker/offscreen hosting is not part of the frozen stable surface. */
export async function create_offscreen_chart(
  gpu_canvas: OffscreenCanvas,
  fallback_canvas: OffscreenCanvas,
  init: offscreen_chart_init,
): Promise<offscreen_chart> {
  await ensure_init();
  const width = Math.max(init.width, 1);
  const height = Math.max(init.height, 1);
  const dpr = Math.max(init.dpr, Number.EPSILON);
  const options = init.options ?? {};
  const { theme, wheel_behavior, price_axis_wheel_zoom, engine: engine_options } = split_offscreen_options(options);
  const wasm = await wasm_create_offscreen_chart(
    gpu_canvas,
    fallback_canvas,
    width,
    height,
    dpr,
    options.backend === "canvas2d",
    false,
    init.force_fallback_adapter === true,
  );
  const selected_theme = theme ?? default_theme_name;
  wasm.apply_options(JSON.stringify(theme_options(theme_palette(selected_theme))));
  if (Object.keys(engine_options).length > 0) {
    wasm.apply_options(JSON.stringify(engine_options));
  }
  const initial_kind = init.series_kind ?? "candlestick";
  if (initial_kind === "footprint") {
    if (wasm.add_footprint_series(true, "{}") === 0xffffffff) {
      throw new AerisChartsError("invalid_options", "default footprint series was rejected");
    }
  } else {
    wasm.set_series_type(KIND_TO_U8[initial_kind]);
  }
  const chart = new offscreen_chart(
    wasm, gpu_canvas, fallback_canvas, width, height, dpr,
    wheel_behavior ?? "auto", price_axis_wheel_zoom ?? false, selected_theme,
  );
  chart.render();
  return chart;
}
